# .github/workflows/run_scripts.yml

name: Run Data and Alert Scripts

# Defines WHEN the automation runs
on:
  # This runs the job automatically on a schedule
  schedule:
    # "cron" syntax: runs at minute 15, 30, 45, and 0 of every hour.
    - cron: '*/15 * * * *'
  
  # This allows you to run the job manually from the "Actions" tab on GitHub
  workflow_dispatch:

jobs:
  run-backend-tasks:
    # Use a standard, free virtual machine provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Set up a Python environment on the virtual machine
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install all the libraries your scripts need
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
      
      # Step 4: Create the secret file securely for this job
      - name: Create secrets.toml file from repository secret
        env:
          # This pulls your GitHub Repository Secret into the job
          STREAMLIT_SECRETS: ${{ secrets.STREAMLIT_SECRETS }}
        run: |
          # Ensure the target directory exists
          mkdir -p .streamlit
          # Use single quotes to treat the secret as plain text
          echo '${{ secrets.STREAMLIT_SECRETS }}' > .streamlit/secrets.toml
      
      # Step 5: Run the data collection script
      - name: Run Data Collection Script
        run: python datacollection.py
      
      # Step 6: Run the notification engine script
      - name: Run Notification Engine Script
        run: python notification_engine.py